server:
  port: 8765
  address: localhost
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由，利用微服务名进行路由,好像无影响
          lower-case-service-id: true
      routes:
      - id: route_service_order
        uri: ${test.uri} #lb表示是微服务
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1


test:
  uri: lb://tams-order
